### ISSUE TITLE
Getting a 443 error when creating a session through Firebase Cloud Functions

### ISSUE THREAD

**Issue by donbytyqi** [opentok/opentok-node#193]
Here's the code:

`
     exports.createNewOpenTokSession = functions.https.onRequest((req, res) => {

	// user who requested to create the session
    const userId = req.query.userId;

    if (userId === null || userId === undefined || userId === "") {
    	return res.send("User id must not be empty.");
    }

    const opentok = new OpenTok(constants.apiKey, constants.apiSecret);

    opentok.createSession(function(err, session) {
	  	if (err) return console.log(err);
	  	var token = session.generateToken();
        console.log(token);
	  	return res.send(token, session.sessionId, userId);
	});

    return res.send("");
    });
`

This is what I get in the console: 

`Error: Failed to createSession. Error: The request failed: Error: getaddrinfo ENOTFOUND api.opentok.com api.opentok.com:443
    at createSessionCallback (/user_code/node_modules/opentok/lib/opentok.js:1034:16)
    at Request._callback (/user_code/node_modules/opentok/lib/client.js:57:14)
    at self.callback (/user_code/node_modules/opentok/node_modules/request/request.js:185:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/user_code/node_modules/opentok/node_modules/request/request.js:881:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)`

**Comment by donbytyqi** [comment]
Apparently I have to upgrade to a paid plan to make external API calls, this was buried deep in the website so I couldn't find it :/, sorry, case closed
